export const projects = [
	{
		img: 'https://user-images.githubusercontent.com/53153822/143931821-e4a554d2-891b-4a92-a962-678d12a762d7.png',
		title: 'Lynda clone',
		des: 'Lynda is an E-learning Platform by LinkedIn. Built with HTML,CSS, and Js.Have features that allow users to buy subscriptions after creating an account on it. Also have features that users sort courses according to views count.',
		demo: '',
		live: 'https://linkedin-learning-clone.herokuapp.com/index', // deployed link
		gitHub: 'https://github.com/RanuRanjan/LyndaClone.github.io',
		technologies: [ 'HTML', 'CSS', 'JavaScript'],
	},
	{
		img: 'https://user-images.githubusercontent.com/53153822/143927187-b3139b2d-6f8c-4f5e-8a6e-e88566577a51.png',
		title: 'Tomtop Clone',
		des: 'An E-commerce website where users can buy any electronics and home accessories products from all over the world.Have features that allow users to add products to the cart, buy them and also sort the products on the basis of price.',
		demo: '',
		live: 'https://ranuranjan.github.io/TomtopClone/',
		gitHub: 'https://github.com/RanuRanjan/TomtopClone',
		technologies: [ 'HTML', 'CSS', 'JavaScript']
	},
	{
		img: 'https://user-images.githubusercontent.com/53153822/141642626-09016284-eeb1-4eec-82b9-92fc31ce5ba8.png',
		title: 'RedBus Clone',
		des: 'RedBus is India’s largest online bus ticketing platform that has transformed bus travel in the country by bringing ease and convenience to millions of Indians who travel using buses.It has features for login/logout . Users can search vehicles according to their needs.Users also book Outstation Vehicle . Users get ticket after successful booking.',
		demo: '',
		live: 'https://front-end-mansur3.vercel.app/',
		gitHub: 'https://github.com/RanuRanjan/Redbus_clone/tree/master',
		technologies: ['React', 'Redux', 'HTML', 'CSS', 'JavaScript','MongoDB'],
	},
	// {
	// 	img: 'https://user-images.githubusercontent.com/73213873/107113597-f547e200-6885-11eb-8abd-72106074907a.png',
	// 	title: 'Clone of Medium',
	// 	des: 'Clone of a blogging web application, Medium where a user can read the blogs written by others and show their response also, one can share their thoughts by posting a blog.',
	// 	demo: '',
	// 	live: 'https://medium-web.netlify.app/',
	// 	gitHub: 'https://github.com/himrd95/Medium-Clone.git',
	// 	technologies: ['React', 'HTML', 'CSS', 'javaScript'],
	// },
	// {
	// 	img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
	// 	title: 'Clone of Fitness Blender',
	// 	des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
	// 	demo: '',
	// 	live: 'https://anshusagar.github.io/FitnessBlender/',
	// 	gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
	// 	technologies: ['HTML', 'CSS', 'javaScript'],
	// },
	// {
	// 	img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
	// 	title: 'Mailchimp Clone',
	// 	des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
	// 	demo: '',
	// 	live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
	// 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
	// 	technologies: ['HTML', 'CSS', 'javaScript'],
	// },
];
